# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ToNgueLP_MW.ui'
#
# Created: Sun Oct  5 12:55:11 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ToNgueLP_MW(object):
    def setupUi(self, ToNgueLP_MW):
        ToNgueLP_MW.setObjectName(_fromUtf8("ToNgueLP_MW"))
        ToNgueLP_MW.resize(910, 611)
        self.centralwidget = QtGui.QWidget(ToNgueLP_MW)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.corpusTabs = QtGui.QTabWidget(self.centralwidget)
        self.corpusTabs.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.corpusTabs.setTabPosition(QtGui.QTabWidget.West)
        self.corpusTabs.setObjectName(_fromUtf8("corpusTabs"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setMinimumSize(QtCore.QSize(216, 0))
        self.frame.setMaximumSize(QtCore.QSize(216, 16777215))
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.searchCase = QtGui.QLineEdit(self.frame)
        self.searchCase.setMinimumSize(QtCore.QSize(200, 0))
        self.searchCase.setMaximumSize(QtCore.QSize(200, 16777215))
        self.searchCase.setObjectName(_fromUtf8("searchCase"))
        self.verticalLayout.addWidget(self.searchCase)
        self.casesList = QtGui.QListView(self.frame)
        self.casesList.setMinimumSize(QtCore.QSize(200, 0))
        self.casesList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.casesList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.casesList.setObjectName(_fromUtf8("casesList"))
        self.verticalLayout.addWidget(self.casesList)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.casesCount = QtGui.QLabel(self.frame)
        self.casesCount.setObjectName(_fromUtf8("casesCount"))
        self.horizontalLayout.addWidget(self.casesCount)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.casesWorkingArea = QtGui.QTabWidget(self.tab)
        self.casesWorkingArea.setObjectName(_fromUtf8("casesWorkingArea"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.sourceDoc = QtGui.QTextEdit(self.tab_3)
        self.sourceDoc.setObjectName(_fromUtf8("sourceDoc"))
        self.verticalLayout_2.addWidget(self.sourceDoc)
        self.sourceInfo = QtGui.QLabel(self.tab_3)
        self.sourceInfo.setObjectName(_fromUtf8("sourceInfo"))
        self.verticalLayout_2.addWidget(self.sourceInfo)
        self.line = QtGui.QFrame(self.tab_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.suspDoc = QtGui.QTextEdit(self.tab_3)
        self.suspDoc.setObjectName(_fromUtf8("suspDoc"))
        self.verticalLayout_2.addWidget(self.suspDoc)
        self.suspInfo = QtGui.QLabel(self.tab_3)
        self.suspInfo.setObjectName(_fromUtf8("suspInfo"))
        self.verticalLayout_2.addWidget(self.suspInfo)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.casesWorkingArea.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.casesWorkingArea.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.casesWorkingArea.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.casesWorkingArea, 0, 1, 1, 1)
        self.corpusTabs.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.corpusTabs.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.corpusTabs, 0, 1, 1, 1)
        ToNgueLP_MW.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ToNgueLP_MW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuCorpus = QtGui.QMenu(self.menubar)
        self.menuCorpus.setObjectName(_fromUtf8("menuCorpus"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuConfig = QtGui.QMenu(self.menubar)
        self.menuConfig.setObjectName(_fromUtf8("menuConfig"))
        self.menuScripts = QtGui.QMenu(self.menubar)
        self.menuScripts.setObjectName(_fromUtf8("menuScripts"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuLogin = QtGui.QMenu(self.menubar)
        self.menuLogin.setObjectName(_fromUtf8("menuLogin"))
        ToNgueLP_MW.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ToNgueLP_MW)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ToNgueLP_MW.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(ToNgueLP_MW)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(48, 48))
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        ToNgueLP_MW.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(ToNgueLP_MW)
        self.toolBar_2.setIconSize(QtCore.QSize(48, 48))
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        ToNgueLP_MW.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBar_2)
        self.actionLoad_New_Corpus = QtGui.QAction(ToNgueLP_MW)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar/icons/menu_corpus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_New_Corpus.setIcon(icon)
        self.actionLoad_New_Corpus.setObjectName(_fromUtf8("actionLoad_New_Corpus"))
        self.actionAdd_New_Corpus_Doc = QtGui.QAction(ToNgueLP_MW)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar/icons/add_corpus_doc.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_New_Corpus_Doc.setIcon(icon1)
        self.actionAdd_New_Corpus_Doc.setObjectName(_fromUtf8("actionAdd_New_Corpus_Doc"))
        self.actionCorpus_Information = QtGui.QAction(ToNgueLP_MW)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar/icons/corpus_info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCorpus_Information.setIcon(icon2)
        self.actionCorpus_Information.setObjectName(_fromUtf8("actionCorpus_Information"))
        self.actionClose_Corpus = QtGui.QAction(ToNgueLP_MW)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar/icons/close_corpus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose_Corpus.setIcon(icon3)
        self.actionClose_Corpus.setObjectName(_fromUtf8("actionClose_Corpus"))
        self.actionAdd_Algorithm_Output = QtGui.QAction(ToNgueLP_MW)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar/icons/add_algorithm_output.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Algorithm_Output.setIcon(icon4)
        self.actionAdd_Algorithm_Output.setObjectName(_fromUtf8("actionAdd_Algorithm_Output"))
        self.actionAdd_New_Case = QtGui.QAction(ToNgueLP_MW)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar/icons/add_case.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_New_Case.setIcon(icon5)
        self.actionAdd_New_Case.setObjectName(_fromUtf8("actionAdd_New_Case"))
        self.actionEdit_Case = QtGui.QAction(ToNgueLP_MW)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar/icons/edit_case.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_Case.setIcon(icon6)
        self.actionEdit_Case.setObjectName(_fromUtf8("actionEdit_Case"))
        self.actionValidate_Case = QtGui.QAction(ToNgueLP_MW)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar/icons/validate_case.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionValidate_Case.setIcon(icon7)
        self.actionValidate_Case.setObjectName(_fromUtf8("actionValidate_Case"))
        self.action_Re_Define_Boundaries = QtGui.QAction(ToNgueLP_MW)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar/icons/redefine_boundaries.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Re_Define_Boundaries.setIcon(icon8)
        self.action_Re_Define_Boundaries.setObjectName(_fromUtf8("action_Re_Define_Boundaries"))
        self.actionView_Annotation = QtGui.QAction(ToNgueLP_MW)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbar/icons/view_annotation.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionView_Annotation.setIcon(icon9)
        self.actionView_Annotation.setObjectName(_fromUtf8("actionView_Annotation"))
        self.actionSave_Corpus = QtGui.QAction(ToNgueLP_MW)
        self.actionSave_Corpus.setObjectName(_fromUtf8("actionSave_Corpus"))
        self.actionSelect_Parser = QtGui.QAction(ToNgueLP_MW)
        self.actionSelect_Parser.setObjectName(_fromUtf8("actionSelect_Parser"))
        self.actionSuggest_Parser = QtGui.QAction(ToNgueLP_MW)
        self.actionSuggest_Parser.setObjectName(_fromUtf8("actionSuggest_Parser"))
        self.actionMain_View = QtGui.QAction(ToNgueLP_MW)
        self.actionMain_View.setObjectName(_fromUtf8("actionMain_View"))
        self.actionComparison_View = QtGui.QAction(ToNgueLP_MW)
        self.actionComparison_View.setObjectName(_fromUtf8("actionComparison_View"))
        self.actionDictionary_View = QtGui.QAction(ToNgueLP_MW)
        self.actionDictionary_View.setObjectName(_fromUtf8("actionDictionary_View"))
        self.actionConvert_Documents = QtGui.QAction(ToNgueLP_MW)
        self.actionConvert_Documents.setObjectName(_fromUtf8("actionConvert_Documents"))
        self.actionVerify_Corpus_and_Parser = QtGui.QAction(ToNgueLP_MW)
        self.actionVerify_Corpus_and_Parser.setObjectName(_fromUtf8("actionVerify_Corpus_and_Parser"))
        self.actionGenerate_Output = QtGui.QAction(ToNgueLP_MW)
        self.actionGenerate_Output.setObjectName(_fromUtf8("actionGenerate_Output"))
        self.actionCompare_Parser_Output_and_XML_Output = QtGui.QAction(ToNgueLP_MW)
        self.actionCompare_Parser_Output_and_XML_Output.setObjectName(_fromUtf8("actionCompare_Parser_Output_and_XML_Output"))
        self.actionGenerate_XML_Output = QtGui.QAction(ToNgueLP_MW)
        self.actionGenerate_XML_Output.setObjectName(_fromUtf8("actionGenerate_XML_Output"))
        self.actionCompare_Parser_and_XML_Output = QtGui.QAction(ToNgueLP_MW)
        self.actionCompare_Parser_and_XML_Output.setObjectName(_fromUtf8("actionCompare_Parser_and_XML_Output"))
        self.actionCompare_XMLs = QtGui.QAction(ToNgueLP_MW)
        self.actionCompare_XMLs.setObjectName(_fromUtf8("actionCompare_XMLs"))
        self.actionUpdate_XMLs_Info = QtGui.QAction(ToNgueLP_MW)
        self.actionUpdate_XMLs_Info.setObjectName(_fromUtf8("actionUpdate_XMLs_Info"))
        self.actionAbout_ToNgueLP = QtGui.QAction(ToNgueLP_MW)
        self.actionAbout_ToNgueLP.setObjectName(_fromUtf8("actionAbout_ToNgueLP"))
        self.actionHelp = QtGui.QAction(ToNgueLP_MW)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionUser_s_Manual = QtGui.QAction(ToNgueLP_MW)
        self.actionUser_s_Manual.setObjectName(_fromUtf8("actionUser_s_Manual"))
        self.menuCorpus.addAction(self.actionLoad_New_Corpus)
        self.menuCorpus.addAction(self.actionAdd_New_Corpus_Doc)
        self.menuCorpus.addAction(self.actionSave_Corpus)
        self.menuCorpus.addAction(self.actionCorpus_Information)
        self.menuCorpus.addAction(self.actionSelect_Parser)
        self.menuCorpus.addAction(self.actionSuggest_Parser)
        self.menuTools.addAction(self.actionMain_View)
        self.menuTools.addAction(self.actionComparison_View)
        self.menuTools.addAction(self.actionDictionary_View)
        self.menuScripts.addAction(self.actionConvert_Documents)
        self.menuScripts.addAction(self.actionVerify_Corpus_and_Parser)
        self.menuScripts.addAction(self.actionGenerate_XML_Output)
        self.menuScripts.addAction(self.actionCompare_XMLs)
        self.menuScripts.addAction(self.actionUpdate_XMLs_Info)
        self.menuHelp.addAction(self.actionAbout_ToNgueLP)
        self.menuHelp.addAction(self.actionUser_s_Manual)
        self.menubar.addAction(self.menuCorpus.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuConfig.menuAction())
        self.menubar.addAction(self.menuScripts.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuLogin.menuAction())
        self.toolBar.addAction(self.actionLoad_New_Corpus)
        self.toolBar.addAction(self.actionAdd_New_Corpus_Doc)
        self.toolBar.addAction(self.actionCorpus_Information)
        self.toolBar.addAction(self.actionClose_Corpus)
        self.toolBar.addAction(self.actionAdd_Algorithm_Output)
        self.toolBar_2.addAction(self.actionAdd_New_Case)
        self.toolBar_2.addAction(self.actionEdit_Case)
        self.toolBar_2.addAction(self.actionValidate_Case)
        self.toolBar_2.addAction(self.action_Re_Define_Boundaries)
        self.toolBar_2.addAction(self.actionView_Annotation)

        self.retranslateUi(ToNgueLP_MW)
        self.corpusTabs.setCurrentIndex(0)
        self.casesWorkingArea.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ToNgueLP_MW)

    def retranslateUi(self, ToNgueLP_MW):
        ToNgueLP_MW.setWindowTitle(QtGui.QApplication.translate("ToNgueLP_MW", "ToNgueLP", None, QtGui.QApplication.UnicodeUTF8))
        self.searchCase.setPlaceholderText(QtGui.QApplication.translate("ToNgueLP_MW", "Search case?", None, QtGui.QApplication.UnicodeUTF8))
        self.casesCount.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Total: 10", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceDoc.setHtml(QtGui.QApplication.translate("ToNgueLP_MW", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">By Earth911</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Wednesday, June 20, 2007</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic; color:#00ff00;\">In United States, about half the air pollution comes from cars and trucks. Two important ways to reduce air pollution are to drive less, even a little less, and to drive smart. Taking fewer trips in your car or truck helps cut air pollution. And adopting smart driving habits reduces your car’s emissions.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic; color:#00ff00;\">Driving less doesn’t mean you have to stay home. Try combining driving with alternative modes of transportation</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Carpool.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Walk or ride a bicycle.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Shop by phone or mail.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ride public transit.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Driving smart keeps pollution at a minimum</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Accelerate gradually.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Use cruise control on the highway.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Obey the speed limit.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Combine your errands into one trip.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Keep your car tuned and support the smog check program.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Don’t top off at the gas pumps.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Replace your car’s air filter.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Keep your tires properly inflated.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">What about smoking vehicles?</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Contact the EPA’s Office of Air Quality Planning &amp; Standards,</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">When<span style=\" color:#000000;\"> shopping for your next car</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">Look for the most efficient, lowest polluting model–or even use either a non-polluting car or zero emission vehicle. Check out these Web sites for information that will help you identify clean and fuel efficient vehicles in any part of the country:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceInfo.setText(QtGui.QApplication.translate("ToNgueLP_MW", "id = 278, src_name = src-doc45, length = 570 chars 70 words 5 sentences, orig_offset = 329", None, QtGui.QApplication.UnicodeUTF8))
        self.suspDoc.setHtml(QtGui.QApplication.translate("ToNgueLP_MW", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">At this stage of research, scientists can not firmly link global warming to changes in circulation patterns. But one study by British and Italian scientists, reported recently in the journal Nature, examined data on atmospheric circulation over the  last 50 years  in the  Northern Hemisphere . <span style=\" font-style:italic; color:#ff0000;\">The researchers looked to see whether there had been any change in frequency of large-scale circulation regimes. The data revealed that there had : in recent decades, patterns had shifted to favor a warmer climate for most land areas in the  Northern Hemisphere . In a general warming of the globe, the air above those land areas would be expected to warm more than that above the oceans, because of differing abilities to absorb heat.</span> But the authors of the new study postulate that the change in circulation patterns is the main reason the land has lately warmed so much. That is, they say, the climate of the hemisphere shifts naturally back and forth between two dominant regimes. Both the  North Atlantic  and  North Pacific  oscillations are believed to be affected by this shift.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.suspInfo.setText(QtGui.QApplication.translate("ToNgueLP_MW", "<html><head/><body><p>id = 367, src_name = susp-doc69, length = 489 chars 67 words 5 sentences, orig_offset = 125</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.casesWorkingArea.setTabText(self.casesWorkingArea.indexOf(self.tab_3), QtGui.QApplication.translate("ToNgueLP_MW", "Case 1", None, QtGui.QApplication.UnicodeUTF8))
        self.casesWorkingArea.setTabText(self.casesWorkingArea.indexOf(self.tab_4), QtGui.QApplication.translate("ToNgueLP_MW", "Case 2", None, QtGui.QApplication.UnicodeUTF8))
        self.casesWorkingArea.setTabText(self.casesWorkingArea.indexOf(self.tab_5), QtGui.QApplication.translate("ToNgueLP_MW", "Compare Cases", None, QtGui.QApplication.UnicodeUTF8))
        self.corpusTabs.setTabText(self.corpusTabs.indexOf(self.tab), QtGui.QApplication.translate("ToNgueLP_MW", "Corpus X", None, QtGui.QApplication.UnicodeUTF8))
        self.corpusTabs.setTabText(self.corpusTabs.indexOf(self.tab_2), QtGui.QApplication.translate("ToNgueLP_MW", "Corpus Y", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCorpus.setTitle(QtGui.QApplication.translate("ToNgueLP_MW", "Corpus", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("ToNgueLP_MW", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConfig.setTitle(QtGui.QApplication.translate("ToNgueLP_MW", "Config", None, QtGui.QApplication.UnicodeUTF8))
        self.menuScripts.setTitle(QtGui.QApplication.translate("ToNgueLP_MW", "Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("ToNgueLP_MW", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLogin.setTitle(QtGui.QApplication.translate("ToNgueLP_MW", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("ToNgueLP_MW", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_2.setWindowTitle(QtGui.QApplication.translate("ToNgueLP_MW", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_New_Corpus.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Load New Corpus", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_New_Corpus_Doc.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Add New Corpus Doc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCorpus_Information.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Corpus Information", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose_Corpus.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Close Corpus", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Algorithm_Output.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Add Algorithm Output", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_New_Case.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Add New Case", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Case.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Edit Case", None, QtGui.QApplication.UnicodeUTF8))
        self.actionValidate_Case.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Validate Case", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Re_Define_Boundaries.setText(QtGui.QApplication.translate("ToNgueLP_MW", "(Re)Define Boundaries", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_Annotation.setText(QtGui.QApplication.translate("ToNgueLP_MW", "View Annotation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Corpus.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Save Corpus", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_Parser.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Select Parser", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSuggest_Parser.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Suggest Parser", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMain_View.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Main View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionComparison_View.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Comparison View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDictionary_View.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Dictionary View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConvert_Documents.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Convert Documents", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVerify_Corpus_and_Parser.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Verify Corpus and Parser", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_Output.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Generate Output", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompare_Parser_Output_and_XML_Output.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Compare Parser Output and XML Output", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_XML_Output.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Generate XML Output", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompare_Parser_and_XML_Output.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Compare Parser and XML Output", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompare_XMLs.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Compare XMLs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate_XMLs_Info.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Update XMLs Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_ToNgueLP.setText(QtGui.QApplication.translate("ToNgueLP_MW", "About ToNgueLP", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("ToNgueLP_MW", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUser_s_Manual.setText(QtGui.QApplication.translate("ToNgueLP_MW", "User\'s Manual", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
